
import java.sql.Connection;
import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANUJ KAUSHAL
 */
public class STUDENTINFO extends javax.swing.JFrame {

    /**
     * Creates new form STUDENTINFO
     */
    public STUDENTINFO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        religon = new javax.swing.ButtonGroup();
        caste = new javax.swing.ButtonGroup();
        department = new javax.swing.ButtonGroup();
        nationality = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jtfdoa = new javax.swing.JTextField();
        jtfdob = new javax.swing.JTextField();
        jtfmobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfpin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfstate = new javax.swing.JTextField();
        jtfcity = new javax.swing.JTextField();
        jtflast = new javax.swing.JTextField();
        jtfaddress = new javax.swing.JTextField();
        jtfmother = new javax.swing.JTextField();
        jtffather = new javax.swing.JTextField();
        jtffirst = new javax.swing.JTextField();
        SUBMIT = new javax.swing.JButton();
        a = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jrbgenderother = new javax.swing.JRadioButton();
        jrbfemale = new javax.swing.JRadioButton();
        jrbmale = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jrbhindu = new javax.swing.JRadioButton();
        jrbjain = new javax.swing.JRadioButton();
        jrbsikh = new javax.swing.JRadioButton();
        jrbreligonother = new javax.swing.JRadioButton();
        jrbmuslim = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jrbst = new javax.swing.JRadioButton();
        jrbgeneral = new javax.swing.JRadioButton();
        jrbobc = new javax.swing.JRadioButton();
        jrbsc = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jrbnri = new javax.swing.JRadioButton();
        jrbindian = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jrbmca = new javax.swing.JRadioButton();
        jrbbecs = new javax.swing.JRadioButton();
        jrbbeit = new javax.swing.JRadioButton();
        jrbbeec = new javax.swing.JRadioButton();
        jrbbeme = new javax.swing.JRadioButton();
        jrbdeptother = new javax.swing.JRadioButton();
        CLEAR = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfenroll = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 10), "STUDENT DATA INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 48), new java.awt.Color(102, 0, 102))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("STATE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("CITY");

        jtfaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfaddressActionPerformed(evt);
            }
        });

        SUBMIT.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SUBMIT.setText("SUBMIT");
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });
        SUBMIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SUBMITKeyReleased(evt);
            }
        });

        a.setBackground(new java.awt.Color(255, 255, 204));
        a.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 5));
        a.setForeground(new java.awt.Color(0, 0, 102));
        a.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));
        jPanel1.setLayout(null);

        gender.add(jrbgenderother);
        jrbgenderother.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbgenderother.setForeground(new java.awt.Color(102, 0, 102));
        jrbgenderother.setText("OTHER");
        jPanel1.add(jrbgenderother);
        jrbgenderother.setBounds(37, 237, 180, 89);

        gender.add(jrbfemale);
        jrbfemale.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbfemale.setForeground(new java.awt.Color(102, 0, 102));
        jrbfemale.setText("FEMALE");
        jPanel1.add(jrbfemale);
        jrbfemale.setBounds(37, 130, 180, 89);

        gender.add(jrbmale);
        jrbmale.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbmale.setForeground(new java.awt.Color(102, 0, 102));
        jrbmale.setText("MALE");
        jPanel1.add(jrbmale);
        jrbmale.setBounds(37, 23, 180, 89);

        a.addTab("GENDER", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 3));
        jPanel3.setLayout(null);

        religon.add(jrbhindu);
        jrbhindu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbhindu.setForeground(new java.awt.Color(0, 153, 153));
        jrbhindu.setText("HINDU");
        jPanel3.add(jrbhindu);
        jrbhindu.setBounds(35, 52, 360, 42);

        religon.add(jrbjain);
        jrbjain.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbjain.setForeground(new java.awt.Color(0, 153, 153));
        jrbjain.setText("JAIN");
        jPanel3.add(jrbjain);
        jrbjain.setBounds(35, 232, 360, 42);

        religon.add(jrbsikh);
        jrbsikh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbsikh.setForeground(new java.awt.Color(0, 153, 153));
        jrbsikh.setText("SIKH");
        jPanel3.add(jrbsikh);
        jrbsikh.setBounds(35, 172, 360, 42);

        religon.add(jrbreligonother);
        jrbreligonother.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbreligonother.setForeground(new java.awt.Color(0, 153, 153));
        jrbreligonother.setText("OTHER");
        jPanel3.add(jrbreligonother);
        jrbreligonother.setBounds(35, 292, 360, 42);

        religon.add(jrbmuslim);
        jrbmuslim.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbmuslim.setForeground(new java.awt.Color(0, 153, 153));
        jrbmuslim.setText("MUSLIM");
        jPanel3.add(jrbmuslim);
        jrbmuslim.setBounds(35, 112, 360, 42);

        a.addTab("RELIGON ", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));
        jPanel2.setLayout(null);

        caste.add(jrbst);
        jrbst.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbst.setForeground(new java.awt.Color(51, 153, 255));
        jrbst.setText("ST");
        jPanel2.add(jrbst);
        jrbst.setBounds(46, 312, 300, 60);

        caste.add(jrbgeneral);
        jrbgeneral.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbgeneral.setForeground(new java.awt.Color(0, 153, 255));
        jrbgeneral.setText("GENERAL");
        jPanel2.add(jrbgeneral);
        jrbgeneral.setBounds(46, 41, 300, 61);

        caste.add(jrbobc);
        jrbobc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbobc.setForeground(new java.awt.Color(51, 153, 255));
        jrbobc.setText("OBC");
        jPanel2.add(jrbobc);
        jrbobc.setBounds(46, 213, 300, 70);

        caste.add(jrbsc);
        jrbsc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbsc.setForeground(new java.awt.Color(51, 153, 255));
        jrbsc.setText("SC");
        jrbsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbscActionPerformed(evt);
            }
        });
        jPanel2.add(jrbsc);
        jrbsc.setBounds(46, 135, 300, 60);

        a.addTab("CASTE", jPanel2);

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
        jPanel4.setLayout(null);

        nationality.add(jrbnri);
        jrbnri.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbnri.setForeground(new java.awt.Color(153, 0, 102));
        jrbnri.setText("NRI");
        jPanel4.add(jrbnri);
        jrbnri.setBounds(50, 180, 370, 100);

        nationality.add(jrbindian);
        jrbindian.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbindian.setForeground(new java.awt.Color(204, 0, 51));
        jrbindian.setText("INDIAN");
        jPanel4.add(jrbindian);
        jrbindian.setBounds(50, 50, 370, 100);

        a.addTab("NATIONALITY", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3));
        jPanel5.setLayout(null);

        department.add(jrbmca);
        jrbmca.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbmca.setForeground(new java.awt.Color(255, 102, 102));
        jrbmca.setText("MCA");
        jPanel5.add(jrbmca);
        jrbmca.setBounds(40, 46, 310, 41);

        department.add(jrbbecs);
        jrbbecs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbbecs.setForeground(new java.awt.Color(255, 102, 102));
        jrbbecs.setText("BE CSE");
        jPanel5.add(jrbbecs);
        jrbbecs.setBounds(40, 95, 310, 41);

        department.add(jrbbeit);
        jrbbeit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbbeit.setForeground(new java.awt.Color(255, 102, 153));
        jrbbeit.setText("BE IT");
        jPanel5.add(jrbbeit);
        jrbbeit.setBounds(40, 187, 310, 41);

        department.add(jrbbeec);
        jrbbeec.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbbeec.setForeground(new java.awt.Color(255, 51, 102));
        jrbbeec.setText("BE EC");
        jPanel5.add(jrbbeec);
        jrbbeec.setBounds(40, 233, 310, 41);

        department.add(jrbbeme);
        jrbbeme.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbbeme.setForeground(new java.awt.Color(255, 102, 102));
        jrbbeme.setText("BE ME");
        jPanel5.add(jrbbeme);
        jrbbeme.setBounds(40, 141, 310, 41);

        department.add(jrbdeptother);
        jrbdeptother.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbdeptother.setForeground(new java.awt.Color(255, 102, 153));
        jrbdeptother.setText("OTHER");
        jPanel5.add(jrbdeptother);
        jrbdeptother.setBounds(40, 279, 310, 41);

        a.addTab("DEPARTMENT", jPanel5);

        CLEAR.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("ENROLLMENT NO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MOTHER'S NAME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("FIRSTNAME");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("DATE OF ADMISSION");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("FATHER'S NAME");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("DATE OF BIRTH");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("ADDRESS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("PINCODE");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("LASTNAME");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("MOBILE NO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfenroll, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtffirst, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtflast, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtffather, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfmother, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfcity, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfstate, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(131, 131, 131)
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfpin, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfdob, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfdoa, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(SUBMIT, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtfenroll, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jtffirst, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jtflast, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jtffather, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jtfmother, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jtfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jtfcity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jtfstate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtfpin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jtfmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jtfdob, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jtfdoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SUBMIT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfaddressActionPerformed

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITActionPerformed
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/anujkaushal","root","anuj");
            String mysql="insert into student_info(enroll_no,firstname,lastname,fathername,mothername,address,city,state,pincode,mobile,dob,doa,gender,religon,caste,nationality,dept) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement smt=con.prepareStatement(mysql);

            String enroll=jtfenroll.getText();
            String first= jtffirst.getText();
            String last=jtflast.getText();
            String father=jtffather.getText();
            String mother=jtfmother.getText();
            String address=jtfaddress.getText();
            String city=jtfcity.getText();
            String state=jtfstate.getText();
            int pin=Integer.parseInt(jtfpin.getText());
            int mobile=Integer.parseInt(jtfmobile.getText());
            String dob=jtfdob.getText();
            String doa=jtfdoa.getText();

            smt.setString(1,enroll);
            smt.setString(2,first);
            smt.setString(3,last );
            smt.setString(4,father);
            smt.setString(5,mother );
            smt.setString(6, address);
            smt.setString(7,city);
            smt.setString(8,state );
            smt.setInt(9,pin );
            smt.setInt(10,mobile);
            smt.setString(11,dob);
            smt.setString(12,doa);
            String gender = null,caste=null,religon=null,nationality=null,dept=null;
            if(jrbmale.isSelected())
            {
                gender=jrbmale.getText();
            }
            if(jrbfemale.isSelected())
            {
                gender=jrbfemale.getText();
            }
            if(jrbgenderother.isSelected())
            {
                gender=jrbgenderother.getText();
            }
            if(jrbindian.isSelected())
            {
                nationality=jrbindian.getText();
            }
            if(jrbnri.isSelected())
            {
                nationality=jrbnri.getText();
            }
            if(jrbgeneral.isSelected())
            {
                caste=jrbgeneral.getText();
            }
            if(jrbst.isSelected())
            {
                caste=jrbst.getText();
            }
            if(jrbsc.isSelected())
            {
                caste=jrbsc.getText();
            }
            if(jrbobc.isSelected())
            {
                caste=jrbobc.getText();
            }
            if(jrbhindu.isSelected())
            {
                religon=jrbhindu.getText();
            }
            if(jrbmuslim.isSelected())
            {
                religon=jrbmuslim.getText();
            }
            if(jrbsikh.isSelected())
            {
                religon=jrbsikh.getText();
            }
            if(jrbjain.isSelected())
            {
                religon=jrbjain.getText();
            }
            if(jrbreligonother.isSelected())
            {
                religon=jrbreligonother.getText();
            }
            if(jrbmca.isSelected())
            {
                dept=jrbmca.getText();
            }
            if(jrbbecs.isSelected())
            {
                dept=jrbbecs.getText();
            }
            if(jrbbeme.isSelected())
            {
                dept=jrbbeme.getText();
            }
            if(jrbbeec.isSelected())
            {
                dept=jrbbeec.getText();
            }
            if(jrbbeit.isSelected())
            {
                dept=jrbbeit.getText();
            }
            if(jrbdeptother.isSelected())
            {
                dept=jrbdeptother.getText();
            }
            smt.setString(13, gender);
            smt.setString(14, religon);
            smt.setString(15, caste);
            smt.setString(16, nationality);
            smt.setString(17, dept);
            smt.executeUpdate();
            JOptionPane.showMessageDialog(null,"insertion complete");
            con.close();

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error In Connectivity");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SUBMITActionPerformed

    private void SUBMITKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SUBMITKeyReleased
        jtfenroll.setEnabled(false);
        jtffirst.setEnabled(false);
        jtflast.setEnabled(false);
        jtffather.setEnabled(false);
        jtfmother.setEnabled(false);
        jtfdoa.setEnabled(false);
        jtfdob.setEnabled(false);
        jtfaddress.setEnabled(false);
        jtfmobile.setEnabled(false);
        jtfcity.setEnabled(false);
        jtfstate.setEnabled(false);
        jtfpin.setEnabled(false);
        jrbmale.setEnabled(false);
        jrbfemale.setEnabled(false);
        jrbgenderother.setEnabled(false);
        jrbhindu.setEnabled(false);
        jrbmuslim.setEnabled(false);
        jrbsikh.setEnabled(false);
        jrbjain.setEnabled(false);
        jrbreligonother.setEnabled(false);
        jrbgeneral.setEnabled(false);
        jrbst.setEnabled(false);
        jrbsc.setEnabled(false);
        jrbobc.setEnabled(false);
        jrbindian.setEnabled(false);
        jrbnri.setEnabled(false);
        jrbmca.setEnabled(false);
        jrbbecs.setEnabled(false);
        jrbbeit.setEnabled(false);
        jrbbeme.setEnabled(false);
        jrbbeec.setEnabled(false);
        jrbdeptother.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_SUBMITKeyReleased

    private void jrbscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbscActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        jtfenroll.setText(null);
        jtffirst.setText(null);
        jtflast.setText(null);
        jtffather.setText(null);
        jtfmother.setText(null);
        jtfdoa.setText(null);
        jtfdob.setText(null);
        jtfaddress.setText(null);
        jtfmobile.setText(null);
        jtfcity.setText(null);
        jtfstate.setText(null);
        jtfpin.setText(null);
        religon.clearSelection();
        caste.clearSelection();
        nationality.clearSelection();
        department.clearSelection();
        gender.clearSelection();
        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        setVisible(false);
        frontpage fp=new frontpage();
        fp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STUDENTINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STUDENTINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STUDENTINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STUDENTINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STUDENTINFO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton SUBMIT;
    private javax.swing.JTabbedPane a;
    private javax.swing.ButtonGroup caste;
    private javax.swing.ButtonGroup department;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jrbbecs;
    private javax.swing.JRadioButton jrbbeec;
    private javax.swing.JRadioButton jrbbeit;
    private javax.swing.JRadioButton jrbbeme;
    private javax.swing.JRadioButton jrbdeptother;
    private javax.swing.JRadioButton jrbfemale;
    private javax.swing.JRadioButton jrbgenderother;
    private javax.swing.JRadioButton jrbgeneral;
    private javax.swing.JRadioButton jrbhindu;
    private javax.swing.JRadioButton jrbindian;
    private javax.swing.JRadioButton jrbjain;
    private javax.swing.JRadioButton jrbmale;
    private javax.swing.JRadioButton jrbmca;
    private javax.swing.JRadioButton jrbmuslim;
    private javax.swing.JRadioButton jrbnri;
    private javax.swing.JRadioButton jrbobc;
    private javax.swing.JRadioButton jrbreligonother;
    private javax.swing.JRadioButton jrbsc;
    private javax.swing.JRadioButton jrbsikh;
    private javax.swing.JRadioButton jrbst;
    private javax.swing.JTextField jtfaddress;
    private javax.swing.JTextField jtfcity;
    private javax.swing.JTextField jtfdoa;
    private javax.swing.JTextField jtfdob;
    private javax.swing.JTextField jtfenroll;
    private javax.swing.JTextField jtffather;
    private javax.swing.JTextField jtffirst;
    private javax.swing.JTextField jtflast;
    private javax.swing.JTextField jtfmobile;
    private javax.swing.JTextField jtfmother;
    private javax.swing.JTextField jtfpin;
    private javax.swing.JTextField jtfstate;
    private javax.swing.ButtonGroup nationality;
    private javax.swing.ButtonGroup religon;
    // End of variables declaration//GEN-END:variables
}
